Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -37,3 +37,5 @@ jobs:
       - name: Pause for 25 seconds
         run: |
           sleep 25
+          echo "For testing failure"
+          exit 1
